export const IDS_MAP = {
    albedo: 'Albedo',
    aloy: 'Aloy',
    amber: 'Amber',
    'arataki-itto': 'Arataki Itto',
    ayaka: 'Kamisato Ayaka',
    ayato: 'Ayato',
    barbara: 'Barbara',
    beidou: 'Beidou',
    bennett: 'Bennett',
    chongyun: 'Chongyun',
    collei: 'Collei',
    diluc: 'Diluc',
    diona: 'Diona',
    eula: 'Eula',
    fischl: 'Fischl',
    ganyu: 'Ganyu',
    gorou: 'Gorou',
    'hu-tao': 'Hu Tao',
    jean: 'Jean',
    kaeya: 'Kaeya',
    kazuha: 'Kaedehara Kazuha',
    keqing: 'Keqing',
    klee: 'Klee',
    kokomi: 'Sangonomiya Kokomi',
    'kuki-shinobu': 'Kuki Shinobu',
    lisa: 'Lisa',
    mona: 'Mona',
    ningguang: 'Ningguang',
    noelle: 'Noelle',
    qiqi: 'Qiqi',
    raiden: 'Raiden Shogun',
    razor: 'Razor',
    rosaria: 'Rosaria',
    sara: 'Kujou Sara',
    sayu: 'Sayu',
    shenhe: 'Shenhe',
    'shikanoin-heizou': 'Shikanoin Heizou',
    sucrose: 'Sucrose',
    tartaglia: 'Tartaglia',
    thoma: 'Thoma',
    tighnari: 'Tighnari',
    'traveler-anemo': 'Traveler Anemo',
    'traveler-dendro': 'Traveler Dendro',
    'traveler-electro': 'Traveler Electro',
    'traveler-geo': 'Traveler Geo',
    venti: 'Venti',
    xiangling: 'Xiangling',
    xiao: 'Xiao',
    xingqiu: 'Xingqiu',
    xinyan: 'Xinyan',
    'yae-miko': 'Yae Miko',
    yanfei: 'Yanfei',
    yelan: 'Yelan',
    yoimiya: 'Yoimiya',
    'yun-jin': 'Yun Jin',
    zhongli: 'Zhongli'
};